version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Start HTTP Server
          command: |
            # Start the HTTP server in the background
            python -m http.server 8000 &
            SERVER_PID=$!  # Save the process ID of the server
            sleep 5  # Wait for the server to start
            echo "HTTP server started with PID: $SERVER_PID"
            # Optional: Check if the server is running
            ps -p $SERVER_PID -o pid,cmd
            wait $SERVER_PID  # Keep the server running

      - run:
          name: Test the server response
          command: |
            sleep 2  # Give some time to ensure the server is up
            curl -f http://localhost:8000/index.html || (echo "Failed to serve index.html" && exit 1)
            echo "Successfully served index.html"

      - run:
          name: Stop the server
          command: |
            kill $SERVER_PID  # Stop the server

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python tests.py  # Specify a command for this step

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
