version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Use a Python Docker image
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install Dependencies
          command: |
            echo "Installing dependencies..."
            pip install -r requirements.txt  # Install dependencies from requirements.txt
      - run:
          name: Run Tests
          command: |
            echo "Running tests..."
            python tests.py  # Run your tests

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deploy
          command: |
            echo "Deploying to production server..."  # Replace with actual deploy commands

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensure deploy runs after build
          filters:
            branches:
              only: master  # Only deploy from the master branch
