version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Use a Python Docker image
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Start HTTP Server
          command: |
            # Start the HTTP server in the background
            python -m http.server 8000 &
            SERVER_PID=$!  # Save the process ID of the server
            sleep 5  # Wait for the server to start
            echo "HTTP server started with PID: $SERVER_PID"
            wait $SERVER_PID  # Keep the server running

      - run:
          name: Test the server response
          command: |
            sleep 2  # Wait to ensure the server is up
            curl -f http://localhost:8000/index.html || (echo "Failed to serve index.html" && exit 1)
            echo "Successfully served index.html"

      - run:
          name: Stop the server
          command: |
            kill $SERVER_PID  # Stop the server

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deploy
          command: |
            echo "Deploying to production server..."  # Replace with actual deploy commands

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensure deploy runs after build
          filters:
            branches:
              only: master  # Only deploy from the master branch
