version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Serve index.html
          command: |
            # Start a simple HTTP server
            python -m http.server 8000 &
            sleep 5  # Wait for the server to start
      - run:
          name: Test the server response
          command: |
            curl -f http://localhost:8000/index.html || (echo "Failed to serve index.html" && exit 1)

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
