name: CI/CD for Static Website

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version suitable for Vercel CLI

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML files
        run: htmlhint ./**/*.html

      - name: Install stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Lint CSS files
        run: stylelint "**/*.css"

  deploy:
    runs-on: ubuntu-latest
    needs: ci  # Ensures this job runs after the CI job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
